version: '3.3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SistemaEventos
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
